### Add stuff
POST http://localhost:8080/stuff
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNjg2ODEzODkxLCJleHAiOjE2ODY5MDAyOTF9.GUzFP4IuKEVJI42mY_9IXWJBuDNz4l6l3_O7Tf52se0

{
  "first_name": "Orzu",
  "last_name": "Mirzayev",
  "role": "teacher",
  "username": "Mirzayev",
  "password": "12345"
}

### List stuff
GET http://localhost:8080/stuff
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNjg3ODQ1MDE1LCJleHAiOjE2ODc5MzE0MTV9.1yOFUBWwowAODXfUA-00ZdcQFJmttrh7kn5Dj5M_3KY
# query params: role, q

### Show single stuff
GET http://localhost:8080/stuff/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2Mzc3NzA1LCJleHAiOjE2ODY0NjQxMDV9.zM2jDB8F7Hvf0XmzJiPgCbP-yyhz-apCF9eGbIf9jps

### Login schema
POST http://localhost:8080/stuff/login
Content-Type: application/json

{
  "username": "Ilnur",
  "password": "ilnur8808"
}

### Update stuff
PATCH http://localhost:8080/stuff/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2Mzc3NzA1LCJleHAiOjE2ODY0NjQxMDV9.zM2jDB8F7Hvf0XmzJiPgCbP-yyhz-apCF9eGbIf9jps
Content-Type: application/json

{
  "first_name": "MuhammadSodiq",
  "last_name": "Mirziyoyev",
  "username": "mirziyoyev" 
}

### Delete stuff
DELETE http://localhost:8080/stuff/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2Mzc3NzA1LCJleHAiOjE2ODY0NjQxMDV9.zM2jDB8F7Hvf0XmzJiPgCbP-yyhz-apCF9eGbIf9jps
